services:
  db:
    image: postgres:14.19
    container_name: simplefoods-db
    env_file:
      - .env.docker
    volumes:
      - ./docker/db/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  app:
    build: .
    container_name: simplefoods-app
    depends_on:
      - db
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
